ignore:
  - "deps/**/*"
coverage:
  range: 70..100
  round: down
  precision: 2
  status:
    project:
      default:
        target: auto
        base: auto
        threshold: 2%
        paths:
          - "src"
          - "lib"
    patch:
      default:
        target: 80%
        threshold: 2%
